### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by lukekoko** [3B-Team4/2021-SES3B-Team4#10]
Hello,

I would like to request the default branch to be renamed something other than master.

Please follow this [guide](https://www.youtube.com/watch?v=dQw4w9WgXcQ) to rename the branch.

Regards,
Luke Kokoftopoulos

**Comment by BerkanYuksel25** [comment]
Thanks for rick-rolling me.

**Comment by lukekoko** [comment]
So... Can you change it? pls respond
